### ISSUE TITLE
Unhandled Exception:  Microsoft.DotNet.Cli.Utils.CommandUnknownException

### ISSUE THREAD

**Issue by michaelmcneilnet** [mrahhal/Migrator.EF6#17]
I am running .Net Core RTM with tooling version 1.0.0-preview2-00312. Migrator.EF6.Tools has appeared correctly in my .nuget/packages/.tools folder after running dotnet restore.

When running 'dotnet ef migrations enable' I get the following error:

```
Unhandled Exception: Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-ef"
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.FindProjectDependencyCommands(String commandName, IEnumerable`1
 commandArgs, String configuration, NuGetFramework framework, String outputPath, String buildBasePath, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.Create(String commandName, IEnumerable`1 args, NuGetFramework f
ramework, String configuration)
   at Microsoft.Extensions.Internal.DotnetToolDispatcher.CreateDispatchCommand(IEnumerable`1 dispatchArgs, NuGetFramework framewor
k, String configuration, String outputPath, String buildBasePath, String projectDirectory, String toolName)
   at Microsoft.Extensions.Internal.DotnetToolDispatcher.CreateDispatchCommand(IEnumerable`1 dispatchArgs, NuGetFramework framewor
k, String configuration, String outputPath, String buildBasePath, String projectDirectory)
   at Migrator.EF6.Tools.Program.Dispatch(String[] args)
   at Migrator.EF6.Tools.Program.Main(String[] args)
```

**Comment by michaelmcneilnet** [comment]
Duplicate of #9
