### ISSUE TITLE
Asp Net Core 1.1 Support

### ISSUE THREAD

**Issue by iyhammad** [mrahhal/Migrator.EF6#31]
Hi,
Is the tool currently compatible with AspNet Core 1.1 Tooling.
If not, is there is a plan for that?
Thanks,

**Comment by mrahhal** [comment]
Hi,

Asp.Net Core 1.1 is just a runtime release (tooling is still the same). So this is still completely compatible with it. If you're facing problems while trying to use it please let me know.

Still, I should probably release an update that uses the `1.1` packages explicitly. (The latest version still works though)

**Comment by mrahhal** [comment]
Still, I should probably release an update that uses the `1.1` packages explicitly. (The latest version still works though)

**Comment by iyhammad** [comment]
Hi,
I've a project and I'm using this tool in it. I've just upgraded it to use csproj file format incited of project.json with VS 2017. when I try to run

```
dotnet ef migrations --help
```

I got the below exception

```
Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'D:\src\SystemX\SystemX.Data\project.json'.
   at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectPath, ProjectReaderSettings settings)
   at Migrator.EF6.Tools.Program.Dispatch(String[] args)
   at Migrator.EF6.Tools.Program.Main(String[] args)
```

Thanks,

**Comment by mrahhal** [comment]
Oh, you're using VS 2017. Sorry but I really have no idea whether the tooling have been updated in 2017 RC. I'll check though.

**Comment by mrahhal** [comment]
@iyhammad as stated [here](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#dncdocker), the tooling in VS 2017 RC is just an early preview and best tried on new and simple projects. It has several known issues.

I won't be able to support that just yet. I plan to support the new tooling when they're released (not the preview) from day 1 though.

**Comment by iyhammad** [comment]
Thank you @mrahhal for your reply. I will wait then and rollback to the json project format.
